### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 1ec5** [1ec5/osmcounts#1]
In 2018, when I last worked on this project, I kept a running to-do list for this project. There’s obviously still much more to do, and it may be necessary to rethink some of the goals.

Milestones:
* [ ] Webpage with sortable tables of POI counts by state
* [ ] …plus sortable tables of road lengths by state — comparable to ImproveOSM
* [ ] …plus completeness and rank — ready to commit
* [ ] …on a choropleth
* [ ] …plus all statistics by core-based statistical area (CBSA) on a bubble map
* [ ] …plus all statistics by county — bloggable
* [ ] …plus island areas, Canada, and Mexico
* [ ] Running weekly
* [ ] Easy to set up — ready for SotMUS

Backend:
* [x] Develop PGSQL query for POIs
* [x] Load Economic Census (ECN) into Postgres
* [x] Load OSM–NAICS correspondence into Postgres
* [x] Fix Alaska
* [x] Performantly query polygons
* [x] Develop PGSQL query for all POIs at once (~ 15 min → 7.6 min; 16 min)
* [x] Load Census state boundaries into Postgres
* [ ] Join POIs w/ ECN
* [ ] Get all-POI query down to 10 minutes
* [ ] Performantly cluster nearby duplicate features
* [ ] Develop PGSQL query for pathways
* [ ] Generalize dual carriageways
* [ ] Load Highway Statistics into Postgres
* [x] Load Census CBSA boundaries into Postgres
* [ ] Load Economic Census for CBSAs
* [ ] Load Economic Census of Island Areas (IA)
* [ ] Load Economic Census County Business Patterns (BP)
* [ ] Load Census county [boundaries](https://www.census.gov/geo/maps-data/data/tiger-cart-boundary.html) into Postgres
* [ ] Break down queries by county
* [ ] Load [HPMS shapefiles](https://www.fhwa.dot.gov/policyinformation/hpms/shapefiles.cfm) into Postgres, especially for [turn lanes](https://www.fhwa.dot.gov/policyinformation/hpms/fieldmanual/page05.cfm#toc505337403) and lane counts
* [ ] Load Ag Census into Postgres
* [ ] Load National Bridge Inventory into Postgres
* [ ] Research Canada NAICS-based statistics
* [ ] Research Mexico NAICS-based statistics

Frontend:
* [ ] Generate TSV files
* [ ] Write simple webpage displaying TSV in tabular format
* [ ] Set up cron job to regenerate statistics
* [ ] Write webpage listing sources and caveats
* [ ] Add state-by-state choropleth map using d3
* [ ] Add county-by-county choropleth map
* [ ] Add toggle between choropleth and bubble map

Logistics:
* [ ] Fully automate data loading
* [ ] Check in scripts
* [ ] Investigate dockerization
